-- 사용자 생성 스크립트

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER test IDENTIFIED BY test;

ALTER USER test DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER test TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO test;

GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO test;

COMMIT;