-- 사용자 생성 스크립트

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER TMDB IDENTIFIED BY TMDB;

ALTER USER TMDB DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER TMDB TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO TMDB;

GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO TMDB;

COMMIT;